{{ config(
    materialized='table',
    engine='MergeTree()',
    order_by=['loan_id'],
    partition_by='toYYYYMM(posted_date)'
) }}
-- Row-per-loan grain that grows unbounded with ingestion volume, so it is
-- partitioned like the raw CDC table (see docs/design-report.md) to keep
-- feature-store rebuilds/backfills scoped to a single month of data.

WITH enriched_loans AS (
    SELECT *
    FROM {{ ref('int_loans_enriched') }}
)

SELECT
    loan_id,
    
    -- Numerical Feature Engineering & Scaling
    loan_amount,
    funded_amount,
    amount_remaining,
    funding_percentage,
    {{ safe_ratio('funded_amount', 'loan_amount', 4) }} AS funding_ratio,

    -- Log Transformation for skewed financial variables (log1p-style shift)
    {{ safe_log10('loan_amount') }} AS log_loan_amount,
    {{ safe_log10('funded_amount') }} AS log_funded_amount,

    -- Categorical One-Hot / Binary Encodings (generated by one_hot_encode)
    sector,
    {{ one_hot_encode('sector', [
        ('is_sector_agriculture', 'Agriculture'),
        ('is_sector_retail', 'Retail'),
        ('is_sector_services', 'Services'),
        ('is_sector_food', 'Food'),
    ]) }},
    country,
    {{ one_hot_encode('country', [
        ('is_country_rwanda', 'Rwanda'),
        ('is_country_kenya', 'Kenya'),
    ]) }},

    -- Temporal Features
    posted_date,
    toMonth(posted_date) AS posted_month,
    toDayOfWeek(posted_date) AS posted_day_of_week,
    dateDiff('day', posted_date, now()) AS days_since_posted,

    -- Machine Learning Target Label (Classification Target)
    CASE 
        WHEN funded_amount >= loan_amount THEN 1 
        ELSE 0 
    END AS target_is_fully_funded

FROM enriched_loans
