apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: true
    basicAuthUser: ${CLICKHOUSE_USER}
    jsonData:
      addCorsHeader: true
      defaultDatabase: analytics
      user: ${CLICKHOUSE_USER}
      username: ${CLICKHOUSE_USER}
    secureJsonData:
      basicAuthPassword: ${CLICKHOUSE_PASSWORD}
      password: ${CLICKHOUSE_PASSWORD}
    editable: false
