apiVersion: 1

datasources:
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: true
    basicAuthUser: inkomoko_admin
    jsonData:
      addCorsHeader: true
      defaultDatabase: analytics
      user: inkomoko_admin
      username: inkomoko_admin
      password: inkomoko_password
    secureJsonData:
      basicAuthPassword: inkomoko_password
      password: inkomoko_password
    editable: true
