apiVersion: 1

contactPoints:
  - orgId: 1
    name: ${ALERT_RECIPIENT_NAME}
    receivers:
      - uid: dfuvdec03lekgb
        type: email
        settings:
          addresses: ${ALERT_RECIPIENT_EMAIL}
          singleEmail: false
        disableResolveMessage: false
