apiVersion: 1

contactPoints:
  - orgId: 1
    name: Biruk Getaneh
    receivers:
      - uid: dfuvdec03lekgb
        type: email
        settings:
          addresses: bkgetmom@gmail.com
          singleEmail: false
        disableResolveMessage: false
